#!/usr/bin/env bash
#
# Infinite loop printing "To infinity and beyond" and reacts to SIGTERM

# Define a function to handle SIGTERM
term_handler() {
    echo "I am invincible!!!"
}

# Trap SIGTERM and call term_handler
trap 'term_handler' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
